# Generated by Django 5.0.7 on 2024-07-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_alter_goods_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods_name',
            new_name='goods_title',
        ),
    ]
